export const BANCOS_CHILE = [
  "BancoEstado",
  "Banco de Chile",
  "Banco Edwards",
  "Banco Internacional",
  "Scotiabank Chile",
  "BCI",
  "Banco BICE",
  "HSBC Bank Chile",
  "Banco Santander Chile",
  "Banco Security",
  "Banco Falabella",
  "Banco Ripley",
  "Banco Consorcio",
  "Banco Itaú",
  "Banco BTG Pactual Chile",
  "Banco do Brasil",
  "JP Morgan Chase Bank",
  "Banco de la Nación Argentina",
  "Coopeuch",
  "Tenpo",
  "MACH",
  "Mercado Pago",
  "Copec Pay",
  "Los Héroes Prepago",
  "Caja Los Andes",
];
